using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Project_app.ORM_classes
{
    public class CountrySet
    {
        public string date { get; set; }
        public int World { get; set; }
        public int Afghanistan { get; set; }
        public int Albania { get; set; }
        public int Algeria { get; set; }
        public int Andorra { get; set; }
        public int Angola { get; set; }
        public int Anguilla { get; set; }
        public int Antigua_and_Barbuda { get; set; }
        public int Argentina { get; set; }
        public int Armenia { get; set; }
        public int Aruba { get; set; }
        public int Australia { get; set; }
        public int Austria { get; set; }
        public int Azerbaijan { get; set; }
        public int Bahamas { get; set; }
        public int Bahrain { get; set; }
        public int Bangladesh { get; set; }
        public int Barbados { get; set; }
        public int Belarus { get; set; }
        public int Belgium { get; set; }
        public int Belize { get; set; }
        public int Benin { get; set; }
        public int Bermuda { get; set; }
        public int Bhutan { get; set; }
        public int Bolivia { get; set; }
        public int Bonaire_Sint_Eustatius_and_Saba { get; set; }
        public int Bosnia_and_Herzegovina { get; set; }
        public int Botswana { get; set; }
        public int Brazil { get; set; }
        public int British_Virgin_Islands { get; set; }
        public int Brunei { get; set; }
        public int Bulgaria { get; set; }
        public int Burkina_Faso { get; set; }
        public int Burundi { get; set; }
        public int Cambodia { get; set; }
        public int Cameroon { get; set; }
        public int Canada { get; set; }
        public int Cape_Verde { get; set; }
        public int Cayman_Islands { get; set; }
        public int Central_African_Republic { get; set; }
        public int Chad { get; set; }
        public int Chile { get; set; }
        public int China { get; set; }
        public int Colombia { get; set; }
        public int Comoros { get; set; }
        public int Congo { get; set; }
        public int Costa_Rica { get; set; }
        public int Cote_d_Ivoire { get; set; }
        public int Croatia { get; set; }
        public int Cuba { get; set; }
        public int Curacao { get; set; }
        public int Cyprus { get; set; }
        public int Czech_Republic { get; set; }
        public int Democratic_Republic_of_Congo { get; set; }
        public int Denmark { get; set; }
        public int Djibouti { get; set; }
        public int Dominica { get; set; }
        public int Dominican_Republic { get; set; }
        public int Ecuador { get; set; }
        public int Egypt { get; set; }
        public int El_Salvador { get; set; }
        public int Equatorial_Guinea { get; set; }
        public int Eritrea { get; set; }
        public int Estonia { get; set; }
        public int Ethiopia { get; set; }
        public int Faeroe_Islands { get; set; }
        public int Falkland_Islands { get; set; }
        public int Fiji { get; set; }
        public int Finland { get; set; }
        public int France { get; set; }
        public int French_Polynesia { get; set; }
        public int Gabon { get; set; }
        public int Gambia { get; set; }
        public int Georgia { get; set; }
        public int Germany { get; set; }
        public int Ghana { get; set; }
        public int Gibraltar { get; set; }
        public int Greece { get; set; }
        public int Greenland { get; set; }
        public int Grenada { get; set; }
        public int Guam { get; set; }
        public int Guatemala { get; set; }
        public int Guernsey { get; set; }
        public int Guinea { get; set; }
        public int Guinea_Bissau { get; set; }
        public int Guyana { get; set; }
        public int Haiti { get; set; }
        public int Honduras { get; set; }
        public int Hungary { get; set; }
        public int Iceland { get; set; }
        public int India { get; set; }
        public int Indonesia { get; set; }
        public int International { get; set; }
        public int Iran { get; set; }
        public int Iraq { get; set; }
        public int Ireland { get; set; }
        public int Isle_of_Man { get; set; }
        public int Israel { get; set; }
        public int Italy { get; set; }
        public int Jamaica { get; set; }
        public int Japan { get; set; }
        public int Jersey { get; set; }
        public int Jordan { get; set; }
        public int Kazakhstan { get; set; }
        public int Kenya { get; set; }
        public int Kosovo { get; set; }
        public int Kuwait { get; set; }
        public int Kyrgyzstan { get; set; }
        public int Laos { get; set; }
        public int Latvia { get; set; }
        public int Lebanon { get; set; }
        public int Lesotho { get; set; }
        public int Liberia { get; set; }
        public int Libya { get; set; }
        public int Liechtenstein { get; set; }
        public int Lithuania { get; set; }
        public int Luxembourg { get; set; }
        public int Macedonia { get; set; }
        public int Madagascar { get; set; }
        public int Malawi { get; set; }
        public int Malaysia { get; set; }
        public int Maldives { get; set; }
        public int Mali { get; set; }
        public int Malta { get; set; }
        public int Marshall_Islands { get; set; }
        public int Mauritania { get; set; }
        public int Mauritius { get; set; }
        public int Mexico { get; set; }
        public int Moldova { get; set; }
        public int Monaco { get; set; }
        public int Mongolia { get; set; }
        public int Montenegro { get; set; }
        public int Montserrat { get; set; }
        public int Morocco { get; set; }
        public int Mozambique { get; set; }
        public int Myanmar { get; set; }
        public int Namibia { get; set; }
        public int Nepal { get; set; }
        public int Netherlands { get; set; }
        public int New_Caledonia { get; set; }
        public int New_Zealand { get; set; }
        public int Nicaragua { get; set; }
        public int Niger { get; set; }
        public int Nigeria { get; set; }
        public int Northern_Mariana_Islands { get; set; }
        public int Norway { get; set; }
        public int Oman { get; set; }
        public int Pakistan { get; set; }
        public int Palestine { get; set; }
        public int Panama { get; set; }
        public int Papua_New_Guinea { get; set; }
        public int Paraguay { get; set; }
        public int Peru { get; set; }
        public int Philippines { get; set; }
        public int Poland { get; set; }
        public int Portugal { get; set; }
        public int Puerto_Rico { get; set; }
        public int Qatar { get; set; }
        public int Romania { get; set; }
        public int Russia { get; set; }
        public int Rwanda { get; set; }
        public int Saint_Kitts_and_Nevis { get; set; }
        public int Saint_Lucia { get; set; }
        public int Saint_Vincent_and_the_Grenadines { get; set; }
        public int San_Marino { get; set; }
        public int Sao_Tome_and_Principe { get; set; }
        public int Saudi_Arabia { get; set; }
        public int Senegal { get; set; }
        public int Serbia { get; set; }
        public int Seychelles { get; set; }
        public int Sierra_Leone { get; set; }
        public int Singapore { get; set; }
        public int Sint_Maarten_Dutch_part { get; set; }
        public int Slovakia { get; set; }
        public int Slovenia { get; set; }
        public int Solomon_Islands { get; set; }
        public int Somalia { get; set; }
        public int South_Africa { get; set; }
        public int South_Korea { get; set; }
        public int South_Sudan { get; set; }
        public int Spain { get; set; }
        public int Sri_Lanka { get; set; }
        public int Sudan { get; set; }
        public int Suriname { get; set; }
        public int Swaziland { get; set; }
        public int Sweden { get; set; }
        public int Switzerland { get; set; }
        public int Syria { get; set; }
        public int Taiwan { get; set; }
        public int Tajikistan { get; set; }
        public int Tanzania { get; set; }
        public int Thailand { get; set; }
        public int Timor { get; set; }
        public int Togo { get; set; }
        public int Trinidad_and_Tobago { get; set; }
        public int Tunisia { get; set; }
        public int Turkey { get; set; }
        public int Turks_and_Caicos_Islands { get; set; }
        public int Uganda { get; set; }
        public int Ukraine { get; set; }
        public int United_Arab_Emirates { get; set; }
        public int United_Kingdom { get; set; }
        public int United_States { get; set; }
        public int United_States_Virgin_Islands { get; set; }
        public int Uruguay { get; set; }
        public int Uzbekistan { get; set; }
        public int Vanuatu { get; set; }
        public int Vatican { get; set; }
        public int Venezuela { get; set; }
        public int Vietnam { get; set; }
        public int Wallis_and_Futuna { get; set; }
        public int Western_Sahara { get; set; }
        public int Yemen { get; set; }
        public int Zambia { get; set; }
        public int Zimbabwe { get; set; }

    }
}
